### ISSUE TITLE
Patent citation data is missing

### ISSUE THREAD

**Issue by crew102** [CSSIP-AIR/PatentsView-API#40]
Nulls are getting returned for the `citedby_patent_number` and `cited_patent_number` fields. For example:

http://www.patentsview.org/api/patents/query?q=%7B%22_begins%22:%7B%22cpc_subgroup_id%22:%22Y10S707/933%22%7D%7D&f=[%22patent_number%22,%22patent_title%22,%22cited_patent_number%22,%22citedby_patent_number%22]&o=%7B%22include_subentity_total_counts%22:false,%22matched_subentities_only%22:true,%22page%22:1,%22per_page%22:25%7D&s=

**Comment by shao-shuai** [comment]
I have the same issue
![image](https://user-images.githubusercontent.com/28980017/51630943-3455a580-1f00-11e9-84e7-2c03e1b3f6ed.png)

**Comment by sarahkelley** [comment]
Thanks for pointing this issue out! We are working on this issue right now and expect to have a fix up by tomorrow!

**Comment by sarahkelley** [comment]
This issue should be resolved now and @crew102 I was able to run your query successfully!

**Comment by crew102** [comment]
It's not running now.

**Comment by sarahkelley** [comment]
Ok, sorry small misunderstanding on my part! Again, we appreciate your patience as we work through the issues we've been having today!

The citation information is available and working, but your particular query still won't run because requesting both the forward and backward citations (ie having both  citing_patent_number and cited_patent_number as fields) is causing an issues on the backend. 

While we work towards a more permanent solution, can you break your query into two (once asking for citing patent number and once for cited patent number) instead?

**Comment by crew102** [comment]
I'll probably just wait until you have a permanent solution. The query is used in a vignette for the patentsview R package and I don't want to introduce a temporary solution into the vignette.

**Comment by crew102** [comment]
Not working for me as of 6:45 on 1/25

**Comment by sarahkelley** [comment]
Ok, we incorrectly thought it was fixed, but it is not! We are in fact working on fixing this right now and will update you once the issue is resolved.

**Comment by sarahkelley** [comment]
@crew102 Should be fixed! Can you test and confirm it is now working for you ?

**Comment by shao-shuai** [comment]
@sarahkelley I just tried, it works well now, thank you.

**Comment by crew102** [comment]
Looks like everything is working, thanks

**Comment by sarahkelley** [comment]
Fantastic! Thanks for your patience!
